//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int SubmissionID { get; set; }
        public int AssignmentID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string Content { get; set; }
        public Nullable<decimal> Grade { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual User User { get; set; }
    }
}
